services:
  mongodb:
    image: mongo:7.0
    container_name: scan-craft-mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    networks:
      - scan-craft-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: scan-craft-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - scan-craft-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: scan-craft-frontend
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - scan-craft-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  scan-craft-network:
    driver: bridge